version: '3'

services:
  
  php-apache:
    build:
      context: .
      dockerfile: dockerfile.php-apache
    container_name: php-apache
    volumes:
      - ./:/var/www/html
    networks:
      - sorteio-net
    ports:
      - "80:80"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_CHARSET: utf8
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./_bd/_data:/var/lib/mysql
      - ./_bd/_dump_bd:/docker-entrypoint-initdb.d
    networks:
      - sorteio-net
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

networks:
  sorteio-net:
    driver: bridge